export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const ACCOUNTHOLDER = 'ACCOUNTHOLDER';
export const ACCOUNTHOLDER_FAILED = 'ACCOUNTHOLDER_FAILED';

export const CHECKING = 'CHECKING';
export const CHECKING_FAILED = 'CHECKING_FAILED';

export const SAVINGS = 'SAVINGS';
export const SAVINGS_FAILED = 'SAVINGS_FAILED';

export const ACCOUNTS = 'ACCOUNTS';
export const ACCOUNTS_FAILED = 'ACCOUNTS_FAILED';

export const CDOFFERINGS = 'CDOFFERINGS';
export const CDOFFERINGS_FAILED = 'CDOFFERINGS_FAILED';