export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const ACCOUNT = 'ACCOUNT';
export const ACCOUNT_FAILED = 'ACCOUNT_FAILED';

export const CHECKING = 'CHECKING';
export const CHECKING_FAILED = 'CHECKING_FAILED';

export const CDOFFERINGS = 'CDOFFERINGS';
export const CDOFFERINGS_FAILED = 'CDOFFERINGS_FAILED';